version: '3.7'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
    restart: always

  pgdb:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=diplom

  celery:
    build: .
    restart: always
    command: celery -A my_diplom worker -l info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - django

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
   postgres_data: null